### ISSUE TITLE
The QC script running on the bam file with all ML m6a values gives the wrong plots

### ISSUE THREAD

**Issue by NurislamSheih** [fiberseq/fiberseq-qc#1]
Hi @mrvollger and @sjneph,

Thank you a lot for your QC script! We found that if we run the QC script on bam files with all m6a ml's starting at 0, we get the wrong QC plots. I uploaded all plots of one sample obtained with and without the addition of -m:
https://drive.google.com/drive/folders/1ddJSVw9qr_xU3yjDmPKYn0kqDmo51Uzm?usp=sharing 

It may seem like a minor issue, but I think adding this point to the wiki would be beneficial.

**Comment by mrvollger** [comment]
Can you share some detail on what you suggest modifying? My thought was, if someone manually lowers the ML threshold I think it would be appropriate for the QC plots to reflect that lower threshold. Don't you think?

FYI, fibertools-rs does some careful work to pick the "right" ml cutoff before spitting out the results so I'd be careful overriding that.

**Comment by NurislamSheih** [comment]
Got it! Thank you. I mean, it would probably be a good idea to mention that if people want to know the quality of the data, it would be a good idea to only run `ft predict-m6a` with the default ML parameter. Something like that.
