### ISSUE TITLE
fiber name modification

### ISSUE THREAD

**Issue by sjneph** [fiberseq/fiberseq-qc#4]
fibers that I've seen usually have some type of name separated by '/' symbol, like: m84046_230715_053754_s4/240455876/ccs

I've been cutting out the middle value (240455876) and using that.  It's not very general, probably, and should be made more robust.

**Comment by mrvollger** [comment]
The PacBio bam specification describes this, basically what you have done should be fine when QCing only one movie.

**Comment by sjneph** [comment]
Stephanie found an issue in creating the randfiber plots when looking at nanopore data.

**Comment by sjneph** [comment]
addressed in commit addb1e4d65a66e4010711a07fb81092ad1389b80
